from __future__ import annotations

import psycopg
from psycopg.rows import dict_row

from .config import database_url
from .models import Profile, Project

# Any fixed number works; every process that runs init_db() has to use the same one.
INIT_LOCK_ID = 20261008


def get_connection() -> psycopg.Connection:
    # Without a timeout, an unreachable database would hang every page request.
    return psycopg.connect(database_url(), row_factory=dict_row, connect_timeout=5)


def init_db() -> None:
    # The with block commits at the end, or rolls back if anything raises.
    with get_connection() as connection:
        # Two app processes starting together take turns here.
        connection.execute("SELECT pg_advisory_xact_lock(%s)", (INIT_LOCK_ID,))
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS profile (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                name TEXT NOT NULL,
                title TEXT NOT NULL,
                location TEXT NOT NULL,
                email TEXT NOT NULL,
                linkedin TEXT,
                github TEXT
            )
            """,
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS projects (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL UNIQUE,
                summary TEXT NOT NULL,
                technologies TEXT NOT NULL,
                link TEXT
            )
            """
        )

        connection.execute(
            """
            INSERT INTO profile (id, name, title, location, email, linkedin, github)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (id) DO NOTHING
            """,
            (
                1,
                "Chelsea Huang",
                "Student | Finance, Investing, and Data Analysis",
                "Los Angeles, CA",
                "chelseahuang11@gmail.com",
                "https://www.linkedin.com/in/chelseahuang",
                "https://github.com/chelseahuang11",
            ),
        )

        # Demo projects only fill an empty table, so they never reappear next to real ones.
        has_projects = connection.execute("SELECT 1 FROM projects LIMIT 1").fetchone()
        for project in [] if has_projects else [
            (
                "Investment Screening Dashboard",
                "Built a dashboard to evaluate public market opportunities using structured financial metrics and scenario comparisons.",
                "Python, SQLite, Jinja, FastAPI",
                "https://example.com/project/investment-screening",
            ),
            (
                "Portfolio Strategy Case Study",
                "Created a compact investment memo that compared risk-adjusted return assumptions across multiple sectors and allocation scenarios.",
                "Excel, Analysis, Research",
                "https://example.com/project/portfolio-strategy",
            ),
            (
                "Data Storytelling Project",
                "Used a structured dataset to present key business insights with visual summaries and concise narrative explanations.",
                "SQL, Python, Data Visualization",
                "https://example.com/project/data-storytelling",
            ),
        ]:
            connection.execute(
                """
                INSERT INTO projects (title, summary, technologies, link)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (title) DO NOTHING
                """,
                project,
            )


def get_profile() -> Profile:
    with get_connection() as connection:
        row = connection.execute("SELECT * FROM profile WHERE id = 1").fetchone()

    if row is None:
        raise ValueError("Profile is missing from the database")

    return Profile(
        id=row["id"],
        name=row["name"],
        title=row["title"],
        location=row["location"],
        email=row["email"],
        linkedin=row["linkedin"],
        github=row["github"],
    )


def get_projects() -> list[Project]:
    with get_connection() as connection:
        rows = connection.execute(
            "SELECT * FROM projects ORDER BY id DESC"
        ).fetchall()

    return [
        Project(
            id=row["id"],
            title=row["title"],
            summary=row["summary"],
            technologies=row["technologies"],
            link=row["link"],
        )
        for row in rows
    ]
